- name: Azure (Storage Explorer)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Install Storage Explorer (Linux)
      become: yes
      command: snap install storage-explorer
      args:
        creates: /snap/bin/storage-explorer
      when: not is_mac and not is_wsl
      register: storage_explorer_installed

    - name: Connect Storage Explorer to Password Manager
      become: yes
      command: snap connect storage-explorer:password-manager-service :password-manager-service
      when: storage_explorer_installed.changed

    - name: Ensure local applications folder exists
      become: yes
      file:
        path: /usr/local/share/applications
        state: directory
      when: not is_mac and not is_wsl

    - name: Add Storage Explorer desktop file
      become: yes
      copy:
        src: storage-explorer.desktop
        dest: /usr/local/share/applications/storage-explorer.desktop
      when: not is_mac and not is_wsl

    # macOS

    - name: Install Storage Explorer (macOS)
      homebrew_cask:
        name: microsoft-azure-storage-explorer
      when: is_mac
